# Generated by Django 3.2.3 on 2021-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btForum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_id', models.IntegerField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('average', models.FloatField()),
                ('min7', models.IntegerField()),
                ('max7', models.IntegerField()),
                ('avg7', models.FloatField()),
            ],
            options={
                'db_table': 'ratestats',
            },
        ),
    ]
