# Generated by Django 3.2.3 on 2021-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btForum', '0002_auto_20210602_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='inTopics',
            field=models.ManyToManyField(to='btForum.Topic'),
        ),
    ]
